---
title: "Weekly reports"
output:
  tufte::tufte_html: 
    tufte_features: ["fonts",  "italics"]
  tufte::tufte_handout: default
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)
library(gridExtra)
library(tufte)
```

Every friday at 5pm your team will need to *hand in* a report documenting the progress on your project to date. You will upload the document to your GitHub site.

For the first (5) weeks, you should think as the audience of these reports as your future self^[For some colorful examples of the needs of your future self, read the first 6 pages of [WaveLab and Reproducible Research](https://statweb.stanford.edu/~wavelab/Wavelab_850/wavelab.pdf)], a piece that is over 20 years old, but quite precognizant] and your mentors. The goal is to document coherently the steps you have taken, what you have learned, what are your current stumbling blocks and the directions that you intend to explore next.
In other words, the weekly report should provide a complete view of where you are at so far.

As the summer comes to a close, your weekly reports will start becoming drafts of your final report to your clients. They will still need to document carefully your code and your analysis strategy, but you will be able to trim down the space devoted to directions you might have explored and that you found not productive (always keep a note in, however, to spare anyone else the same work), and you will pay more attention to build a storyline. 

The reports will need to be *live documents* which a reader can use to reproduce your work entirely. To achieve this we will use *R markdown*^[See the [R studio  webpage](https://rmarkdown.rstudio.com) and the book [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)] or *Jupyter notebooks*^[https://jupyter.org/]: your team will be able to chose one or the other, depending on how easily these tools interact with the language you use for the main portion of your analysis. To increase readability, not all of your code will need to be shown explicitly in the report, but it will need to be linked appropriately: Rmarkdown and Jopyter notebooks will allow you to do this elegantly. 

Every week, we will spend some time reflecting together on what are the ingredients of an effective investigation based on data and how to best document it. This will help you become more aware of the choices you make in creating your reports and the graphics they contain. As you start this week, then, remember that this is work in progress and that you are not striving for perfection right away: to start, focus on documenting.   

