---
title: "List of on line resources"
output:
  tufte::tufte_html: 
    tufte_features: ["fonts",  "italics"]
  tufte::tufte_handout: default
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)
library(gridExtra)
library(tufte)
```

This document collects links to on-line resources that we have found helpful for some of our educational purprose.

# Desing thinking in data analysis and graphical displays

- [Katherine Hepworth's reading list](https://kathep.com/tools/readings/)

# Software tools: R Markdown

- [Chapter from Happy Git with R on R Markdow](https://happygitwithr.com/rmd-test-drive.html)
- [Data Challenge Lab's R Markdown basics content](https://dcl-2020-01.github.io/curriculum/rmarkdown-basics.html)
- [A YouTube video from Roger Peng on using R Markdown with Rstudio](https://www.youtube.com/watch?v=DNS7i2m4sB0)
- [Bookdown](https://bookdown.org/yihui/rmarkdown/)
- [CMU intro to Rmd]( http://www.stat.cmu.edu/~cshalizi/rmarkdown/)
- [tufte Rmd style]( http://rstudio.github.io/tufte/)

# Reproducibility workflows

- [Software Carpentry's R for Reproducible Scientific Analysis Lessons](http://swcarpentry.github.io/r-novice-gapminder/)
- [Book on The Practice of Reproducible Research](https://www.practicereproducibleresearch.org/core-chapters/3-basic.html)
- [Chapter on reproducibility](https://statsthinking21.github.io/statsthinking21-core-site/doing-reproducible-research.html)

# Data Science Courses/books

- [Harvard's Intro to Data Science course which is driven by a series of R markdown documents](https://datasciencelabs.github.io/pages/syllabus.html)
- [Statistical thinking for the 21st centrury](https://statsthinking21.org)
- [Modern statistics for modern biology](http://web.stanford.edu/class/bios221/book/)
- [Data 8](http://data8.org)

# Graphics

- [How humans see data](https://www.youtube.com/watch?v=fSgEeI2Xpdc&feature=youtu.be) (video)
- [Chapter](http://web.stanford.edu/class/bios221/book/Chap-Graphics.html)

# Causality

- [Seminar series](https://sites.google.com/view/ocis/home?authuser=0)